# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Unzip test_run
      run: git clone https://github.com/Marcelektro/MavenMCP-1.8.9 && cp /home/runner/work/AlbinoClient/AlbinoClient/MavenMCP-1.8.9/* /home/runner/work/AlbinoClient/AlbinoClient

    - name: add libraries
      run: cd test_native && wget https://github.com/JnCrMx/discord-game-sdk4j/releases/download/v0.5.5/windows-amd64-discord_game_sdk_jni.dll

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
